// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCYD0E_YTqRoxTNeKwx3GZ91ucjhHpsc',
    appId: '1:190168461546:web:be160b6a57dd98d8d3e793',
    messagingSenderId: '190168461546',
    projectId: 'panda-chat-8ecf9',
    authDomain: 'panda-chat-8ecf9.firebaseapp.com',
    storageBucket: 'panda-chat-8ecf9.appspot.com',
    measurementId: 'G-XH95NN1TZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQfsPXi91hGaWscHCZlWC5RhuJxfdIknc',
    appId: '1:190168461546:android:7f5ade9d9586e1bed3e793',
    messagingSenderId: '190168461546',
    projectId: 'panda-chat-8ecf9',
    storageBucket: 'panda-chat-8ecf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK3P1tXsKJgoGoYReKX1rl1Rr6csNCg6s',
    appId: '1:190168461546:ios:2ec7fb04b3e68705d3e793',
    messagingSenderId: '190168461546',
    projectId: 'panda-chat-8ecf9',
    storageBucket: 'panda-chat-8ecf9.appspot.com',
    iosClientId: '190168461546-ep58ahp07rts9oijdklk2s57090blhk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK3P1tXsKJgoGoYReKX1rl1Rr6csNCg6s',
    appId: '1:190168461546:ios:2ec7fb04b3e68705d3e793',
    messagingSenderId: '190168461546',
    projectId: 'panda-chat-8ecf9',
    storageBucket: 'panda-chat-8ecf9.appspot.com',
    iosClientId: '190168461546-ep58ahp07rts9oijdklk2s57090blhk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandachat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfCYD0E_YTqRoxTNeKwx3GZ91ucjhHpsc',
    appId: '1:190168461546:web:ea5af216d1aa5c49d3e793',
    messagingSenderId: '190168461546',
    projectId: 'panda-chat-8ecf9',
    authDomain: 'panda-chat-8ecf9.firebaseapp.com',
    storageBucket: 'panda-chat-8ecf9.appspot.com',
    measurementId: 'G-QB3J4PR57D',
  );
}
